name: LSTM Model CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Create Project Directory
      run: mkdir /my_lstm_project

    - name: Copy Files
      run: |
        cp run.py /my_lstm_project/run.py
        cp Dockerfile /my_lstm_project/Dockerfile
        cp bat_with_temp.csv /my_lstm_project/bat_with_temp.csv

    - name: Build Docker Image
      run: docker build -t lstm-model /my_lstm_project

    - name: Run Docker Container
      run: docker run lstm-model
